services:
  db:
    container_name: cv_db
    image: mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  nginx:
    build: 
      context: ./docker
      dockerfile: Dockerfile-nginx
    container_name: cv_nginx
    links:
      - php
    ports:
      - "222:80"
    volumes:
      - ./:/var/www/curriculum-vitae:cached
  node:
    command: sh ./watch.sh
    container_name: cv_node
    depends_on: 
      - php
    image: node:20-alpine
    ports:
      - "8080:8082"
    restart: on-failure
    volumes:
      - ./:/var/www/curriculum-vitae:cached
    working_dir: /var/www/curriculum-vitae
  phpmyadmin:
    container_name: cv_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - UPLOAD_LIMIT=300M
  php:
    build: 
      context: ./docker
      dockerfile: Dockerfile-php
    container_name: cv_php
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - PHP_UPLOAD_MAX_FILESIZE=100MB
      - PHP_MEMORY_LIMIT=128M
    links:
      - db
    volumes:
      - ./:/var/www/curriculum-vitae:cached
volumes:
  db: